# Internal + external pathway course text for all 12 primary meridians.
# Sourced from: (1) Dr. Zhang's own weekly lecture slides/transcripts, already
# extracted and verified in earlier per-week Study Guide builds this term
# (LU/LI = Week 2, HT/SI = Week 4, PC/SJ/GB/LR = Week 6); (2) the Week 5
# live-class transcript, directly, for BL/KI (never built before -- this was
# the genuine gap); (3) ST/SP written fresh to stay consistent with the
# already-published Exam Trap ("ST truly begins at LI20, not ST1") rather
# than reusing an earlier simplified draft that contradicted it.

PATHWAY_COURSE = {
    "LU": [
        "Originates in the Middle Burner (Middle Jiao), descends to connect with the LARGE INTESTINE (interior-exterior pairing)",
        "Turns back, winds along the upper orifice of the stomach, passes through the diaphragm, enters the LUNG (pertaining organ)",
        "From the \u2018Lung system\u2019 (the portion communicating with the throat), emerges transversely below the clavicle at LU1 Zhongfu",
        "Descends along the medial aspect of the upper arm, passing IN FRONT of the HT and PC channels",
        "Reaches the cubital fossa (elbow), continues down the anterior border of the radial side of the forearm",
        "Enters \u2018cunkou\u2019 at the wrist -- the radial artery pulse-taking site -- passing LU9 Taiyuan",
        "Along the thenar eminence, radial border, ending at the medial side of the thumb tip, LU11 Shaoshang",
        "BRANCH: emerges from LU7 Lieque near the wrist, runs directly to the radial side of the index finger tip -> LI1 Shangyang, linking to LARGE INTESTINE",
    ],
    "LI": [
        "Begins at the radial side of the tip of the index finger, LI1 Shangyang -- same finger where LU's branch terminates",
        "Runs upward along the radial side of the index finger, through the web between the 1st/2nd metacarpal bones (LI4 Hegu)",
        "Dips into the depression between the extensor pollicis longus/brevis tendons, follows the lateral-anterior forearm to the lateral elbow, up to the shoulder (LI15 Jianyu)",
        "Along the anterior border of the acromion, ascends to C7 (GV14 Dazhui) -- the meeting point of ALL SIX Yang channels of hand and foot",
        "Descends to the supraclavicular fossa, connects internally with the LUNG, passes through the diaphragm, PERTAINS Large Intestine",
        "BRANCH: from the supraclavicular fossa, ascends the neck, passes through the cheek, enters the gums of the LOWER teeth",
        "Curves around the upper lip, CROSSES to the opposite side at the philtrum (GV26 area) -- left meridian goes right, right goes left",
        "Ends beside the nostril at LI20 Yingxiang, where LI links with the STOMACH meridian of Foot-Yangming",
    ],
    "ST": [
        "TRUE ORIGIN is LI20 Yingxiang (a crossing point of the LI channel) beside the nose -- NOT ST1, which is only the first NUMBERED point on ST's own sequence",
        "Ascends to the bridge of the nose, crosses BL1 at the inner canthus, descends along the lateral side of the nose to enter the upper gum",
        "Curves around the lips, descends to meet CV24, runs along the lower jaw, ascends in front of the ear to the forehead",
        "BRANCH: from the lower jaw (ST5 area), descends through the neck to ST9, then to the supraclavicular fossa, through the diaphragm, PERTAINS Stomach, connects with SPLEEN",
        "EXTERNAL branch: from the supraclavicular fossa, descends past the nipple (ST17, landmark only -- never needled), alongside the umbilicus, to ST30 in the groin",
        "Continues down the anterior thigh and leg (the longest single run of any channel -- 45 points, the most of any primary meridian)",
        "Crosses the dorsum of the foot, ends at the lateral side of the 2nd toe, ST45 -- hands off to SPLEEN at the toes",
    ],
    "SP": [
        "Begins at the medial side of the big toe tip, SP1 Yinbai",
        "Runs along the medial border of the foot, past the medial malleolus (SP6, the classic Three-Yin intersection point)",
        "At 8 CUN above the medial malleolus, crosses IN FRONT of the LIVER channel (the one distribution exception among all 12 primary meridians -- below 8 cun SP runs posterior to LR, above 8 cun SP moves anterior)",
        "Ascends the medial thigh, enters the abdomen, PERTAINS Spleen, connects with STOMACH",
        "BRANCH: from the stomach, ascends through the diaphragm, spreads through the chest, alongside the esophagus, connects with the root of the tongue and spreads over its LOWER surface",
        "EXTERNAL portion continues from the abdomen up the side of the trunk to SP21 Dabao (the Great/Major Luo of Spleen, on the lateral chest)",
        "BRANCH: from the stomach, through the diaphragm, pours into the HEART -- linking SP to the next channel, HT",
    ],
    "HT": [
        "Originates in the Heart, emerges from the system of blood vessels surrounding the Heart",
        "Descends through the diaphragm to connect with the SMALL INTESTINE (interior-exterior pairing)",
        "BRANCH: ascends alongside the esophagus, crosses the face and cheek, connects with the tissues surrounding the eye (the \u2018eye system\u2019)",
        "The main external pathway emerges from the axilla at HT1 Jiquan",
        "Descends along the postero-medial aspect of the arm (posterior to LU and PC channels) to the elbow at HT3 Shaohai",
        "Continues along the medial/ulnar aspect of the forearm to the wrist at HT7 Shenmen (pisiform bone)",
        "Travels through the palm along the radial side of the little finger",
        "Ends at HT9 Shaochong, radial tip of the little finger nail -- hands off to SMALL INTESTINE",
    ],
    "SI": [
        "Begins at SI1 Shaoze, ulnar side of the little finger tip -- where HT's branch terminates",
        "Runs along the ulnar/dorsal aspect of the hand and forearm, through SI3 Houxi and SI5 Yanggu",
        "Crosses the elbow at SI8 Xiaohai (He-Sea), ascends the posterior aspect of the upper arm",
        "Circles the shoulder joint (SI9-SI10), zigzags across the scapula (SI11-SI13)",
        "Crosses GV14 Dazhui at the top of the shoulder, enters the supraclavicular fossa",
        "Descends internally to the HEART, through the diaphragm, reaches the Stomach, PERTAINS Small Intestine",
        "BRANCH: from the neck, ascends the cheek to the outer canthus, enters the ear at SI19 Tinggong",
        "SECOND BRANCH: from the cheek, ascends to the inner canthus (crosses BL1 Jingming), then to the cheekbone (crosses GB14 Yangbai)",
    ],
    "BL": [
        "Begins at the inner canthus, BL1 Jingming -- where SI's branch terminates",
        "Ascends to the forehead, joins the Governing Vessel at the vertex (GV20) -- a branch splits off here to the temple",
        "The straight portion continues internally from the vertex to communicate with the brain, then re-emerges to descend the posterior neck",
        "Splits into TWO parallel lines running the full length of the back, alongside the spine, down to the lumbar region -- these run SIMULTANEOUSLY, not sequentially (confirmed directly by Dr. Zhang in Q&A)",
        "The medial (1.5-cun) line enters the body at the lumbar region, connects internally with the KIDNEY, and PERTAINS Bladder",
        "A branch from this internal connection descends through the buttock to the popliteal fossa",
        "The lateral (3-cun) line runs alongside the medial line down the back, through the buttock (crossing GB30 Huantiao), down the posterior thigh, and MEETS the medial line's branch at the popliteal fossa",
        "From the popliteal fossa, descends along the posterior calf, behind the lateral malleolus, along the 5th metatarsal, ending at the lateral tip of the little toe, BL67 Zhiyin -- hands off to KIDNEY",
    ],
    "KI": [
        "Begins on the sole of the foot, below the little toe, at KI1 Yongquan -- where BL's course ends",
        "Emerges below the tuberosity of the navicular bone, runs behind the medial malleolus, and enters the heel (this is why KI is the answer for heel pain -- its pathway curves directly behind the medial malleolus and through the heel)",
        "Ascends along the medial leg to the popliteal fossa, then up the postero-medial thigh, through the spine",
        "Enters the body, connects internally with the BLADDER, PERTAINS Kidney",
        "The straight portion continues upward from the Kidney, through the Liver and diaphragm, into the Lung, along the throat, terminating at the root of the tongue",
        "BRANCH: separates from the Lung, connects with the Heart, continues into the chest -- links with the PERICARDIUM meridian of Hand-Jueyin",
        "67 points total (KI1 Yongquan to KI27 Shufu) -- despite fewer points than BL, KI connects internally with more organs (Kidney, Bladder, Liver, Lung, Heart) than almost any other channel",
    ],
    "PC": [
        "Originates in the chest, emerges and enters its pertaining organ, the Pericardium",
        "Descends through the diaphragm to the abdomen, connecting successively with the Upper, Middle, and Lower Jiao (San Jiao)",
        "BRANCH: from inside the chest, emerges at the costal region 3 cun below the anterior axillary fold (PC1 Tianchi), ascends to the axilla",
        "Runs down the medial aspect of the upper arm, BETWEEN the Lung channel (anterior) and Heart channel (posterior)",
        "Crosses the cubital fossa (PC3 Quze), continues down the forearm between the tendons of palmaris longus and flexor carpi radialis",
        "Crosses the wrist (PC7 Daling), through the palm (PC8 Laogong), ending at the tip of the middle finger (PC9 Zhongchong)",
        "BRANCH: arises from the palm at PC8 Laogong, runs along the ring finger to its tip, links with the SAN JIAO channel",
    ],
    "SJ": [
        "Originates at the tip of the ring finger (SJ1 Guanchong)",
        "Runs upward between the 4th and 5th metacarpal bones, along the dorsal wrist, to the lateral forearm between radius and ulna",
        "Passes the olecranon, ascends the lateral upper arm, reaches the shoulder -- crosses BEHIND the Gallbladder channel there",
        "Winds to the supraclavicular fossa, spreads in the chest to connect with the Pericardium",
        "Descends through the diaphragm to the abdomen, enters its pertaining organ: Upper, Middle, and Lower Jiao",
        "BRANCH: from the chest, ascends through the supraclavicular fossa, up the neck, along the posterior border of the ear, to the corner of the anterior hairline, then turns down to the cheek, terminates infraorbitally",
        "BRANCH (auricular): arises retroauricularly, enters the ear, exits in front of the ear, crosses the cheek branch, reaches SJ23 Sizhukong, links with the GALLBLADDER channel at the outer canthus",
    ],
    "GB": [
        "Originates at the outer canthus (GB1 Tongziliao)",
        "Ascends to the corner of the forehead (GB4 Hanyan), then curves down to the retroauricular region (GB20 Fengchi)",
        "Runs along the side of the neck, in FRONT of San Jiao to the shoulder, then turns back and crosses BEHIND San Jiao, down to the supraclavicular fossa",
        "BRANCH (head): from behind the ear, enters the ear, exits in front, to the posterior aspect of the outer canthus",
        "BRANCH (canthus): from the outer canthus down to the ST5/6 region, meets San Jiao infraorbitally, descends to the neck, rejoins the main channel at the supraclavicular fossa",
        "MAIN INTERNAL branch: from the supraclavicular fossa, descends through the diaphragm, connects with the Liver, enters its pertaining organ the Gallbladder; continues through the hypochondriac region, emerges at the inguinal region, circles the pubic hair margin, transverses to the hip (GB30 Huantiao)",
        "STRAIGHT/EXTERNAL portion: from the supraclavicular fossa, descends in front of the axilla, along the lateral chest and free ends of the floating ribs (GB24-GB25), to the hip where it joins the internal branch (GB30)",
        "Continues down the lateral thigh and knee, along the anterior fibula, to GB39 Xuanzhong, in front of the external malleolus, along the dorsum of the foot to the lateral tip of the 4th toe (GB44)",
        "BRANCH: from the dorsum of the foot, to the great toe, links with the LIVER channel",
    ],
    "LR": [
        "Begins at the lateral side of the great toe (LR1 Dadun), runs along the dorsum of the foot",
        "At 8 cun above the medial malleolus, crosses IN FRONT of the Spleen channel (the exception to the usual anterior/middle/posterior leg-Yin order)",
        "Ascends the medial knee and thigh to the pubic region, circles the genitals, enters the lower abdomen",
        "Curves around the Stomach, enters the Liver (its pertaining organ), connects with the Gallbladder",
        "Continues up through the diaphragm, spreads through the costal/hypochondriac region",
        "Ascends along the posterior trachea/throat, connects with the eye system, EMERGES AT THE FOREHEAD, meets the Governing Vessel AT THE VERTEX (GV20 Baihui) -- unique among primary channels for reaching the vertex",
        "BRANCH (cheek): from the eye system, descends to the cheek, circles the inner lips",
        "BRANCH (internal): from the Liver, through the diaphragm, into the Lung, connects with the LUNG channel -- completes the 12-channel cycle back to LU",
    ],
}
