# Content data for weekly Cram Sheets, keyed by week number.
# All facts sourced from verified special-point data already used in the
# Midterm Cram Sheet / Study Guide / Practice Midterm, plus standard,
# well-established TCM pathway knowledge. Crossing-point counts for LU/LI
# are noted conservatively since no Week 2 lecture transcript exists to
# verify Dr. Zhang's specific framing (unlike ST/SP/HT/SI which do have
# transcripts).

WEEKS = {
    2: dict(
        abbrev_pair="LU & LI",
        channel_names="Lung & Large Intestine Channels",
        pts_line="LU (11 pts) + LI (20 pts) = 31 Points",
        cover_special=["LU7, LI4", "and all categories"],
        crossing_summary=["Minimal (LU) /", "GV14 + face (LI)"],
        this_week_abbrevs=["LU", "LI"],
        channels=[
            dict(
                name="Lung", classification="Hand Taiyin", npts=11, polarity="Yin",
                element="Metal", peak="3-5 AM", direction_short="Chest to Hand (anteromedial)",
                id_card=[
                    ("Full name", "Lung Meridian of Hand-Taiyin"),
                    ("Points / Clock", "11 pts | 3-5 AM"),
                    ("Element / Polarity", "Metal | Yin"),
                    ("Direction", "Chest -> Hand (anteromedial)"),
                    ("Pertains / Connects", "Lung / Large Intestine"),
                    ("Back-Shu / Front-Mu", "BL13 Feishu / LU1 Zhongfu (own)"),
                    ("Yuan-Source", "LU9 Taiyuan"),
                    ("Luo-Connecting", "LU7 Lieque"),
                    ("Xi-Cleft", "LU6 Kongzui"),
                    ("He-Sea", "LU5 Chize"),
                    ("Confluent + Command", "LU7 \u2014 opens Ren Mai + commands head/neck"),
                    ("First / Last", "LU1 Zhongfu / LU11 Shaoshang"),
                ],
                pathway_beats=[
                    "Originates in the Middle Burner (stomach region), descends to connect with the Large Intestine (interior-exterior pairing)",
                    "Turns back, encircles the cardia (stomach opening), ascends through the diaphragm, enters the LUNG (pertaining organ)",
                    "From the throat/lung system, emerges transversely below the clavicle at LU1 Zhongfu (own Front-Mu) - surface pathway begins here",
                    "Descends along the antero-lateral (radial) aspect of the upper arm, anterior to the HT and PC channels",
                    "Crosses the elbow crease at LU5 Chize (He-Sea), continues along the radial border of the forearm",
                    "Enters the 'inch opening' at the wrist (radial pulse-taking site), passes LU9 Taiyuan (Yuan-Source)",
                    "Along the thenar eminence, ends at the radial side of the thumb tip, LU11 Shaoshang",
                    "BRANCH: from LU7 Lieque near the wrist, splits to the radial tip of the index finger -> LI1 Shangyang, handing off to LARGE INTESTINE",
                ],
                five_shu=[("Jing-Well", "Wood", "LU11"), ("Ying-Spring", "Fire", "LU10"),
                          ("Shu-Stream", "Earth", "LU9"), ("Jing-River", "Metal", "LU8"),
                          ("He-Sea", "Water", "LU5")],
                n_crossing="minimal",
                crossing_points=[
                    ("(none clearly enumerated)", "LU's surface pathway begins independently at LU1 - unlike LI/ST, it is not commonly taught with a numbered list of external crossing points. Confirm with Dr. Zhang if tested."),
                ],
                highest_yield=[
                    ("LU7", "Luo + Confluent + Command", "Opens Ren Mai; commands head/neck; classic point for cough, headache, stiff neck"),
                    ("LU9", "Yuan-Source + Shu-Stream", "Radial pulse site; tonifies Lung Qi, chronic cough/asthma"),
                    ("LU5", "He-Sea", "Clears heat, descends rebellious Lung Qi; cough, asthma, acute throat"),
                    ("LU1", "Front-Mu (own)", "Chest fullness, grief/sadness, cough - diagnostic point for Lung"),
                    ("LU11", "Jing-Well", "Sore throat, fever, loss of consciousness - emergency point"),
                ],
                exam_traps=[
                    "LU1 is the Lung's OWN Front-Mu point - unusual, since most Front-Mu points sit on the Ren Mai or another channel.",
                    "LU9 doubles as both Shu-Stream AND Yuan-Source - true for every Yin channel's Shu-Stream point.",
                    "LU7 carries THREE special categories at once (Luo, Confluent, Command) - the most loaded point in the Weeks 1-4 scope alongside SI3.",
                    "LU connects to LI, NOT to any other channel - sets up the Anterior Circuit's first hand-off.",
                ],
            ),
            dict(
                name="Large Intestine", classification="Hand Yangming", npts=20, polarity="Yang",
                element="Metal", peak="5-7 AM", direction_short="Hand to Head (lateral anterior)",
                id_card=[
                    ("Full name", "Large Intestine Meridian of Hand-Yangming"),
                    ("Points / Clock", "20 pts | 5-7 AM"),
                    ("Element / Polarity", "Metal | Yang"),
                    ("Direction", "Hand -> Head (lateral anterior)"),
                    ("Pertains / Connects", "Large Intestine / Lung"),
                    ("Back-Shu / Front-Mu", "BL25 Dachangshu / ST25 Tianshu (on ST channel)"),
                    ("Yuan-Source", "LI4 Hegu \u2014 FORBIDDEN in pregnancy"),
                    ("Luo-Connecting", "LI6 Pianli"),
                    ("Xi-Cleft", "LI7 Wenliu"),
                    ("He-Sea", "LI11 Quchi"),
                    ("Command", "LI4 \u2014 commands face/mouth"),
                    ("First / Last", "LI1 Shangyang / LI20 Yingxiang"),
                ],
                pathway_beats=[
                    "Begins at the radial side of the tip of the index finger, LI1 Shangyang - the same finger where LU's branch terminates",
                    "Runs along the back of the hand, wrist, and forearm (radial side) through LI4 Hegu",
                    "Crosses the elbow at LI11 Quchi (He-Sea), up the antero-lateral upper arm to the shoulder (LI15)",
                    "Meets GV14 Dazhui at the top of the shoulder - the meeting point of ALL SIX Yang channels",
                    "Enters the supraclavicular fossa, descends internally to connect with the LUNG, through the diaphragm, PERTAINS Large Intestine",
                    "BRANCH: from the supraclavicular fossa, ascends the neck, crosses the cheek, enters the LOWER GUM",
                    "Curves around the upper lip, crosses to the OPPOSITE side at the philtrum (GV26 area)",
                    "Ends beside the nostril at LI20 Yingxiang, handing off to the STOMACH channel (ST begins here)",
                ],
                five_shu=[("Jing-Well", "Metal", "LI1"), ("Ying-Spring", "Water", "LI2"),
                          ("Shu-Stream", "Wood", "LI3"), ("Jing-River", "Fire", "LI5"),
                          ("He-Sea", "Earth", "LI11")],
                n_crossing=2,
                crossing_points=[
                    ("GV14 Dazhui", "meeting point of all 6 Yang channels; fever, neck stiffness"),
                    ("LI20 / ST1 area", "LI's endpoint hands directly into the ST channel's origin"),
                ],
                highest_yield=[
                    ("LI4", "Yuan-Source + Command (face/mouth)", "FORBIDDEN in pregnancy; face/mouth disorders, headache, general analgesic point"),
                    ("LI11", "He-Sea", "Clears heat, especially heat in the Blood; fever, skin disorders, hypertension"),
                    ("LI20", "Crossing to ST", "Nasal congestion, loss of smell, facial paralysis"),
                    ("LI1", "Jing-Well", "Sore throat, fever, loss of consciousness"),
                ],
                exam_traps=[
                    "LI has nearly DOUBLE the points of its paired LU channel (20 vs. 11) - point count doesn't track Yin/Yang status consistently.",
                    "LI4 is FORBIDDEN in pregnancy - one of only two forbidden points in the Weeks 1-4 scope (with SP6).",
                    "LI's Front-Mu is ST25 (on the STOMACH channel, not its own) - unlike LU, which has its own Front-Mu.",
                    "LOWER teeth/gums = LI. UPPER teeth/gums = ST. A classic exam-trap pair.",
                    "LI connects to STOMACH, not Spleen - a common circuit-continuity trap.",
                ],
            ),
        ],
        only_list=[
            ("Point that is Lung's OWN Front-Mu (unusual)", "LU1 Zhongfu"),
            ("Point carrying 3 special categories at once (Wk 2)", "LU7 Lieque"),
            ("LOWER teeth/gums meridian", "LI"),
            ("Meeting point of ALL 6 Yang channels", "GV14 Dazhui (on LI's pathway)"),
            ("LI has how many more points than LU?", "9 more (20 vs. 11)"),
        ],
        forbidden_pregnancy=[
            "LI4 Hegu \u2014 moves Qi and Blood downward, strong descending action.",
            "(SP6 Sanyinjiao is also forbidden \u2014 taught in Week 3, cumulative through the midterm.)",
        ],
        last_60_seconds=[
            "LU = 11 pts, 3-5 AM, Yin Metal, chest to hand, LU1 own Front-Mu, LU7 triple-loaded.",
            "LI = 20 pts, 5-7 AM, Yang Metal, hand to head, LI4 forbidden in pregnancy, LOWER teeth.",
            "LU connects to LI. LI connects to ST (NOT Spleen) \u2014 first hand-off of the Anterior Circuit.",
            "LI4 and LU7 are the two most commonly tested points in this pair \u2014 know both cold.",
        ],
        commonly_confused=[
            ("LU7 vs LI4", "LU7 = command HEAD/NECK + opens Ren Mai. LI4 = command FACE/MOUTH, FORBIDDEN in pregnancy."),
            ("LU1 vs ST25", "LU1 = Lung's OWN Front-Mu. ST25 = Front-Mu of LI, sits on the STOMACH channel."),
            ("Upper vs Lower teeth", "UPPER teeth = ST channel. LOWER teeth = LI channel."),
        ],
    ),
    4: dict(
        abbrev_pair="HT & SI",
        channel_names="Heart & Small Intestine Channels",
        pts_line="HT (9 pts) + SI (19 pts) = 28 Points",
        cover_special=["HT7, SI3", "and all categories"],
        crossing_summary=["HT: 0 (unique)", "SI: BL1, GB14"],
        this_week_abbrevs=["HT", "SI"],
        channels=[
            dict(
                name="Heart", classification="Hand Shaoyin", npts=9, polarity="Yin",
                element="Fire", peak="11 AM-1 PM", direction_short="Chest to Hand (posterior medial)",
                id_card=[
                    ("Full name", "Heart Meridian of Hand-Shaoyin"),
                    ("Points / Clock", "9 pts | 11 AM-1 PM"),
                    ("Element / Polarity", "Fire | Yin"),
                    ("Direction", "Chest -> Hand (posterior medial)"),
                    ("Pertains / Connects", "Heart / Small Intestine"),
                    ("Back-Shu / Front-Mu", "BL15 Xinshu / CV14 Juque"),
                    ("Yuan-Source", "HT7 Shenmen (also Shu-Stream)"),
                    ("Luo-Connecting", "HT5 Tongli"),
                    ("Xi-Cleft", "HT6 Yinxi"),
                    ("He-Sea", "HT3 Shaohai"),
                    ("Crossing points", "ZERO \u2014 the only primary channel with none"),
                    ("First / Last", "HT1 Jiquan / HT9 Shaochong"),
                ],
                pathway_beats=[
                    "Originates in the HEART, spreads to the 'Heart system' (linking vessels of heart to other organs)",
                    "Internal branch descends through diaphragm, connects with SMALL INTESTINE (pertaining organ)",
                    "Another internal branch ascends alongside the esophagus, connects to the 'eye system' (brain connection)",
                    "Main external pathway emerges from the heart, spreads to the Lung, then turns down to the axilla (HT1 Jiquan)",
                    "Descends along the postero-medial aspect of the upper arm, posterior to LU and PC channels",
                    "Crosses the elbow at HT3 Shaohai (He-Sea), continues down the forearm's ulnar/medial border",
                    "Enters the wrist at HT7 Shenmen (Shu-Stream + Yuan-Source) - calms the Shen",
                    "Continues along the palm, ends at the radial side of the little finger tip, HT9 Shaochong \u2014 hands off to SMALL INTESTINE",
                ],
                five_shu=[("Jing-Well", "Wood", "HT9"), ("Ying-Spring", "Fire", "HT8"),
                          ("Shu-Stream", "Earth", "HT7"), ("Jing-River", "Metal", "HT4"),
                          ("He-Sea", "Water", "HT3")],
                n_crossing=0,
                crossing_points=[
                    ("(none)", "HT is the only primary channel with ZERO crossing points \u2014 confirmed unique feature, high-yield exam fact."),
                ],
                highest_yield=[
                    ("HT7", "Shu-Stream + Yuan-Source", "Calms Shen; #1 point for anxiety, insomnia, palpitations"),
                    ("HT3", "He-Sea", "Clears heart fire; fear, arm pain along the channel"),
                    ("HT6", "Xi-Cleft", "Night sweats, acute heart pain"),
                    ("HT9", "Jing-Well", "Emergency point: severe heart pain, palpitations, revives consciousness"),
                    ("HT5", "Luo-Connecting", "Links to SI; treats disorders of both channels"),
                ],
                exam_traps=[
                    "HT has only 9 points \u2014 the FEWEST of any primary channel.",
                    "HT7 doubles as Shu-Stream AND Yuan-Source \u2014 true for every Yin channel.",
                    "HT has ZERO crossing points \u2014 do not confuse with SI, which crosses BL1 and GB14.",
                    "HT and SI are primary Fire; do NOT lump them with PC/SJ (Ministerial Fire) \u2014 different circuits.",
                    "HT connects to SI, completing the Fire pair that opens the Posterior/Inner Circuit.",
                ],
            ),
            dict(
                name="Small Intestine", classification="Hand Taiyang", npts=19, polarity="Yang",
                element="Fire", peak="1-3 PM", direction_short="Hand to Head (posterior lateral)",
                id_card=[
                    ("Full name", "Small Intestine Meridian of Hand-Taiyang"),
                    ("Points / Clock", "19 pts | 1-3 PM"),
                    ("Element / Polarity", "Fire | Yang"),
                    ("Direction", "Hand -> Head (posterior lateral)"),
                    ("Pertains / Connects", "Small Intestine / Heart"),
                    ("Back-Shu / Front-Mu", "BL27 Xiaochangshu / CV4 Guanyuan"),
                    ("Yuan-Source", "SI4 Wangu"),
                    ("Luo-Connecting", "SI7 Zhizheng"),
                    ("Xi-Cleft", "SI6 Yanglao"),
                    ("Shu-Stream + Confluent", "SI3 Houxi \u2014 opens Du Mai"),
                    ("Lower He-Sea (of SI)", "ST39 Xiajuxu \u2014 on the ST channel, not SI itself"),
                    ("First / Last", "SI1 Shaoze / SI19 Tinggong"),
                ],
                pathway_beats=[
                    "Begins at the ulnar side of the tip of the little finger, SI1 Shaoze \u2014 where HT's branch terminates",
                    "Runs along the ulnar/posterior border of the hand and forearm, through SI3 Houxi (Shu-Stream + Confluent, opens Du Mai)",
                    "Crosses the elbow (SI8 Xiaohai, He-Sea), up the posterior aspect of the upper arm",
                    "Circles around the shoulder, zigzags across the scapula, crosses GV14 Dazhui",
                    "Enters supraclavicular fossa, descends internally to the HEART, through diaphragm, PERTAINS Small Intestine",
                    "BRANCH: from the neck, ascends the cheek, crosses cheekbone, reaches the outer canthus, enters the ear at SI19 Tinggong",
                    "Second BRANCH: from the cheek, ascends to the inner canthus of the eye (crosses BL1), then to the cheekbone (crosses GB14)",
                    "SI19 near the ear is the pathway's endpoint; the eye-branch connects toward the BLADDER channel",
                ],
                five_shu=[("Jing-Well", "Metal", "SI1"), ("Ying-Spring", "Water", "SI2"),
                          ("Shu-Stream", "Wood", "SI3"), ("Jing-River", "Fire", "SI5"),
                          ("He-Sea", "Earth", "SI8")],
                n_crossing=2,
                crossing_points=[
                    ("BL1 Jingming", "inner canthus of eye \u2014 SI's branch crosses here en route to BL"),
                    ("GB14 Yangbai", "forehead \u2014 second facial crossing point on SI's ascending branch"),
                ],
                highest_yield=[
                    ("SI3", "Shu-Stream + Confluent", "Opens Du Mai (pairs with BL62); spine, neck, febrile disease"),
                    ("SI4", "Yuan-Source", "Wrist/finger pain, febrile disease"),
                    ("SI8", "He-Sea", "Elbow/arm disorders, mental-emotional Fire patterns"),
                    ("SI19", "Last point (near ear)", "Tinnitus, deafness, ear disorders"),
                    ("SI1", "Jing-Well", "Excess breast milk / lactation problems \u2014 specifically noted by Dr. Zhang"),
                ],
                exam_traps=[
                    "SI has MORE than double HT's points (19 vs. 9) \u2014 same pattern as LU (11) / LI (20).",
                    "SI's Lower He-Sea is ST39 \u2014 located on the STOMACH channel, not on SI itself. Lower He-Sea points for Fu organs all sit on leg-yang channels.",
                    "SI crosses BL1 and GB14 \u2014 do not confuse with HT, which has zero crossing points.",
                    "SI3 opens the Du Mai (pairs with BL62) \u2014 not the Ren Mai and not the Chong Mai.",
                    "SI connects to HT, completing the hand-off that opened this week's Fire pair.",
                ],
            ),
        ],
        only_list=[
            ("ONLY primary channel with ZERO crossing points", "HT"),
            ("Fewest total points of any primary channel", "HT \u2014 9 pts"),
            ("SI's Lower He-Sea sits on which channel?", "ST (ST39 Xiajuxu)"),
            ("SI3 opens which Extraordinary Vessel?", "Du Mai (pairs w/ BL62)"),
            ("HT7 doubles as which two categories?", "Shu-Stream + Yuan-Source"),
        ],
        forbidden_pregnancy=[
            "(No new forbidden points introduced in HT/SI \u2014 cumulative list remains LI4 and SP6 from Weeks 2-3.)",
        ],
        last_60_seconds=[
            "HT = 9 pts, 11 AM-1 PM, Yin Fire, chest to hand, ZERO crossing points, HT7 calms Shen.",
            "SI = 19 pts, 1-3 PM, Yang Fire, hand to head, crosses BL1 + GB14, Lower He-Sea is ST39.",
            "HT and SI are PRIMARY Fire \u2014 do not confuse with PC/SJ's Ministerial Fire circuit.",
            "Posterior/Inner Circuit begins here: HT -> SI -> (BL -> KI next week).",
            "SI3 opens Du Mai. HT has no confluent point at all.",
        ],
        commonly_confused=[
            ("HT vs SI point count", "HT = 9 (fewest of any channel). SI = 19 (more than double its Yin partner)."),
            ("HT crossing vs SI crossing", "HT = ZERO crossing points. SI crosses BL1 and GB14."),
            ("Primary Fire vs Ministerial Fire", "HT/SI = primary Fire circuit. PC/SJ = Ministerial Fire, a separate circuit (Week 6)."),
            ("SI3 vs LI4", "SI3 = Confluent, opens Du Mai (spine). LI4 = Command of face/mouth."),
        ],
    ),
}
