# Week 6 Quiz Kit -- 30 MCQ questions covering PC, SJ, GB, LR.
# Each tuple: (question, [A,B,C,D], correct_letter, explanation)
# Grounded in wk6_content.py (transcript-verified + standard Deadman/CAM values).

QUESTIONS = [
    # ---- PC (7 questions) ----
    ("What is the pertaining organ of the Pericardium meridian?",
     ["Heart", "Pericardium", "San Jiao", "Small Intestine"], "B",
     "PC's pertaining organ is directly named in the channel's own title -- Pericardium."),
    ("How many crossing points does the PC channel have?",
     ["0", "2", "9", "14"], "A",
     "PC has ZERO crossing points -- the exam trap identical to HT; only these two primary channels have none."),
    ("Direction of Qi flow in the PC meridian?",
     ["Chest to hand", "Hand to head", "Head to foot", "Foot to chest"], "A",
     "PC is a Hand-Yin channel; all three Hand-Yin channels (LU, HT, PC) flow chest to hand."),
    ("PC runs on the arm in which position relative to LU and HT?",
     ["Anterior to both", "Posterior to both", "Between LU (anterior) and HT (posterior)", "Between HT (anterior) and LU (posterior)"], "C",
     "PC runs the MIDDLE line of the arm -- between LU (anterior) and HT (posterior). Exam-testable 'in-between' position."),
    ("Which PC point is BOTH Luo-Connecting and a Confluent point (opens Yin Wei Mai)?",
     ["PC3", "PC6", "PC7", "PC8"], "B",
     "PC6 Neiguan is Luo-Connecting AND opens the Yin Wei Mai (paired with SP4)."),
    ("PC's Yuan-Source point is:",
     ["PC3 Quze", "PC6 Neiguan", "PC7 Daling", "PC9 Zhongchong"], "C",
     "PC7 Daling is both Shu-Stream and Yuan-Source, at the midpoint of the wrist crease."),
    ("How many total points does the PC channel have?",
     ["6", "9", "12", "19"], "B",
     "PC has 9 points (PC1-PC9) -- fewest of any Yin channel except HT."),

    # ---- SJ (8 questions) ----
    ("What is the connecting organ of the San Jiao meridian?",
     ["Gallbladder", "Liver", "Pericardium", "Bladder"], "C",
     "SJ (San Jiao) pairs with Pericardium as its Yin-Yang interior-exterior partner."),
    ("SJ5 Waiguan opens which Extraordinary Vessel?",
     ["Dai Mai", "Yang Wei Mai", "Yin Wei Mai", "Chong Mai"], "B",
     "SJ5 is the confluent point opening the Yang Wei Mai, paired with GB41."),
    ("At the shoulder, how does the SJ channel relate to the GB channel?",
     ["SJ never crosses GB", "SJ crosses GB once, in front only", "They cross TWICE -- GB in front, then SJ crosses back behind", "SJ and GB run parallel, never touching"], "C",
     "Per the transcript: GB runs in front of SJ to the shoulder, then turns back and crosses behind SJ -- the two Shaoyang channels cross each other twice in that region."),
    ("San Jiao's active hours are:",
     ["7-9 PM", "9-11 PM", "11 PM-1 AM", "1-3 AM"], "B",
     "SJ is active 9-11 PM (Hai) -- per the transcript, this is why we should be resting during this window, since San Jiao 'connects all organs.'"),
    ("How many points does the SJ channel have?",
     ["9", "14", "23", "44"], "C",
     "SJ has 23 points (SJ1-SJ23)."),
    ("SJ's Front-Mu point is:",
     ["CV5 Shimen", "CV17 Danzhong", "GB24 Riyue", "BL22 Sanjiaoshu"], "A",
     "SJ's Front-Mu is CV5 Shimen; its Back-Shu is BL22 Sanjiaoshu."),
    ("SJ17 Yifeng is a crossing point most associated with treating:",
     ["Vertex headache", "Tinnitus, deafness, facial paralysis", "Forbidden in pregnancy", "Nausea and vomiting"], "B",
     "SJ17 Yifeng, posterior to the earlobe, is a high-yield point for ear disorders -- tinnitus, deafness, TMJ, facial paralysis."),
    ("SJ's Lower He-Sea point (used for Fu-organ disorders, located on the leg) is:",
     ["SJ10 Tianjing", "GB34 Yanglingquan", "BL39 Weiyang", "ST36 Zusanli"], "C",
     "SJ's Lower He-Sea is BL39 Weiyang -- NOT on the SJ channel itself, the same trap structure as other Fu organs' lower he-sea points."),

    # ---- GB (8 questions) ----
    ("How many points does the GB channel have, and where does that rank it?",
     ["23 -- 4th largest", "44 -- 3rd largest after BL and ST", "67 -- largest of all", "14 -- smallest Yang channel"], "B",
     "GB has 44 points, the 3rd largest channel after BL (67) and ST (45)."),
    ("GB's course on the head is uniquely described as:",
     ["A straight line", "A zigzag / 'Z-shape'", "A circle around the ear only", "It doesn't reach the head"], "B",
     "GB's head course is a distinctive zigzag ('Z-shape'), unique among the 12 primary channels -- exam-testable visual signature."),
    ("Which GB point is FORBIDDEN in pregnancy?",
     ["GB20", "GB21", "GB34", "GB40"], "B",
     "GB21 Jianjing has a strong descending action that can induce labor -- forbidden in pregnancy, same trap category as LI4 and SP6."),
    ("GB34 Yanglingquan holds which dual special-point designation?",
     ["Yuan-Source + Luo-Connecting", "He-Sea + Hui-Meeting of Sinews/Tendons", "Xi-Cleft + Confluent", "Jing-Well + Back-Shu"], "B",
     "GB34 is both the He-Sea point AND the Hui-Meeting point for Sinews/Tendons -- master point for tendon/ligament disorders."),
    ("GB41 Zulinqi is the confluent point opening which Extraordinary Vessel?",
     ["Yang Wei Mai", "Yin Qiao Mai", "Dai Mai (Girdle Vessel)", "Ren Mai"], "C",
     "GB41 opens the Dai Mai, paired with SJ5 -- the only channel whose confluent point connects to a vessel that encircles the waist."),
    ("Alternating fever/chills with a bitter taste in the mouth is the classic syndrome pattern for which channel?",
     ["PC", "SJ", "GB (Shaoyang syndrome)", "LR"], "C",
     "This is the classic Shaoyang syndrome, specifically associated with GB per the lecture's repeated emphasis."),
    ("The GB channel crossing-point count on the slide is:",
     ["Fully resolved at 9 points", "Listed as 12, but only 9 are actually named -- unresolved", "0 -- GB has no crossing points", "44, matching its total point count"], "B",
     "Content-integrity flag: the slide states '12 points / 6 meridians' but only 9 points are actually named. Confirm with Dr. Zhang before treating this as settled."),
    ("GB's Back-Shu and Front-Mu points are:",
     ["BL19 Danshu / GB24 Riyue", "BL18 Ganshu / LR14 Qimen", "BL22 Sanjiaoshu / CV5 Shimen", "BL14 Jueyinshu / CV17 Danzhong"], "A",
     "GB's Back-Shu is BL19 Danshu; its Front-Mu is its own point, GB24 Riyue."),

    # ---- LR (7 questions) ----
    ("Which meridian crosses IN FRONT of the Liver meridian at a point 8 cun above the medial malleolus?",
     ["The Spleen meridian", "The Kidney meridian", "The Stomach meridian", "The Gallbladder meridian"], "A",
     "The Spleen channel crosses in front of Liver at 8 cun above the medial malleolus -- the ONE exception to the usual medial-leg Yin channel order."),
    ("The Liver channel is the only primary channel that reaches:",
     ["The ear", "The vertex (GV20)", "The nipple", "The heel"], "B",
     "LR uniquely reaches the vertex and meets the Governing Vessel at GV20 Baihui -- vertex headache is a classic Liver-channel presentation."),
    ("LR3 pairs with which point to form the classic 'Four Gates' combination?",
     ["LI4", "ST36", "SP6", "HT7"], "A",
     "LR3 Taichong + LI4 Hegu = the 'Four Gates,' a classic combination to move Qi and Blood, taught this week."),
    ("LR13 Zhangmen carries which double special-point designation?",
     ["Yuan-Source + Luo-Connecting", "Front-Mu of Spleen + Hui-Meeting of all 5 Zang", "He-Sea + Xi-Cleft", "Jing-Well + Back-Shu"], "B",
     "LR13 is the Front-Mu point of the SPLEEN (not Liver) AND the Hui-Meeting point for all 5 Zang organs -- a classic mix-up on exams."),
    ("How many points does the LR channel have?",
     ["9", "14", "23", "44"], "B",
     "LR has 14 points (LR1-LR14) -- the smallest Yin channel of the foot."),
    ("LR's active hours, and what happens if a patient wakes during this window?",
     ["7-9 PM -- treat Pericardium", "1-3 AM -- treat Liver function first", "3-5 AM -- treat Lung function first", "11 PM-1 AM -- treat Gallbladder"], "B",
     "LR is active 1-3 AM (Chou). Per the transcript, waking specifically in this window points to treating the Liver first; waking 3-5 AM points to the Lung instead."),
    ("Direction of Qi flow in the Liver meridian?",
     ["Chest to hand", "Hand to head", "Head to foot", "Foot to chest"], "D",
     "LR is a Foot-Yin channel; all three Foot-Yin channels (SP, LR, KI) flow foot to chest/abdomen."),
]

assert len(QUESTIONS) == 30, f"Expected 30 questions, got {len(QUESTIONS)}"
