# AC300 Practice Midterm - Weeks 1-4 (Channel Theory, LU/LI, ST/SP, HT/SI)
# 28 questions: mixed MC / True-False / EXCEPT format
# Several items adapted directly from the verified Week 3 Quiz Kit per Dr. Zhang's
# note that the midterm reuses quiz material.

SECTIONS = [
    ("CHANNEL THEORY & CIRCADIAN CLOCK", "Week 1", [
        dict(n=1, type="EXCEPT",
             q="The three-part naming convention for a primary meridian includes all of the following EXCEPT:",
             opts=["Hand/Foot (location)", "Yin/Yang (medial/lateral surface, nature)",
                   "Zang/Fu (pertaining organ)", "Element (Five-Phase assignment)"],
             ans="D",
             exp="The naming convention has exactly 3 parts: Hand/Foot + Yin/Yang + Zang/Fu (e.g. \"Hand Taiyin Lung\"). Element (Metal, Earth, Fire...) is a separate Five-Phase classification, not part of the channel's formal name."),
        dict(n=2, type="TF",
             q="True or False: Foot Yang meridians circulate Qi from the head down to the foot.",
             opts=["True", "False"], ans="A",
             exp="Correct direction rule: Hand Yin chest->hand, Hand Yang hand->head, Foot Yang head->foot, Foot Yin foot->chest/abdomen."),
        dict(n=3, type="MC",
             q="Hand Yin and Hand Yang channels hand off Qi to each other at the:",
             opts=["Face", "Fingers", "Toes", "Chest"], ans="B",
             exp="Hand Yin ends and Hand Yang begins at the fingers (e.g. LU7's branch meets LI1 at the index finger). Hand Yang meets Foot Yang at the face; Foot Yang meets Foot Yin at the toes; Foot Yin meets Hand Yin at the chest."),
        dict(n=4, type="MC",
             q="How many total primary (regular) meridians are there in the body?",
             opts=["10", "12", "14", "15"], ans="B",
             exp="3 Hand Yin + 3 Hand Yang + 3 Foot Yin + 3 Foot Yang = 12 Primary Meridians. (The 8 Extraordinary Vessels and 15 Luo-Connecting channels are separate categories, covered later in the course.)"),
        dict(n=5, type="MC",
             q="Which of the following is the correct Zang-Fu (interior-exterior) pairing?",
             opts=["LU - ST", "LU - LI", "LU - SP", "LU - HT"], ans="B",
             exp="LU (Yin/Zang) pairs with LI (Yang/Fu) - both Metal element, both Hand channels. Interior-exterior pairs always share the same element and the same Hand/Foot classification."),
    ]),
    ("LUNG & LARGE INTESTINE", "Week 2", [
        dict(n=6, type="MC",
             q="The Lung channel's full classification is:",
             opts=["Hand Taiyin", "Hand Yangming", "Foot Taiyin", "Foot Yangming"], ans="A",
             exp="LU = Hand Taiyin, Metal, Yin, peak 3-5 AM. Its paired channel LI = Hand Yangming, Metal, Yang, peak 5-7 AM."),
        dict(n=7, type="MC",
             q="How many acupoints does the Lung channel have?",
             opts=["9", "11", "20", "21"], ans="B",
             exp="LU has 11 points, LU1 (Zhongfu) to LU11 (Shaoshang). Its paired LI channel has 20 - nearly double."),
        dict(n=8, type="MC",
             q="LU7 (Lieque) is significant for holding which combination of special categories?",
             opts=["He-Sea + Xi-Cleft", "Luo-Connecting + Confluent (opens Ren Mai) + Command Point (head/neck)",
                   "Jing-Well + Yuan-Source", "Shu-Stream + Back-Shu"], ans="B",
             exp="LU7 is unusually loaded: Luo-Connecting point of LU, a Confluent point opening the Ren Mai, and a Command Point for the head/neck region."),
        dict(n=9, type="MC",
             q="LI4 (Hegu) is best described as:",
             opts=["The He-Sea point of LI, safe throughout pregnancy",
                   "The Yuan-Source point of LI, FORBIDDEN in pregnancy",
                   "The Jing-Well point of LI, used only for fever",
                   "The Xi-Cleft point of LI, used only for acute pain"], ans="B",
             exp="LI4 Hegu is LI's Yuan-Source point and a Command Point for the face/mouth. Its strong descending, Qi/Blood-moving action makes it FORBIDDEN in pregnancy - one of only two pregnancy-forbidden points in the Weeks 1-4 scope (the other is SP6)."),
        dict(n=10, type="TF",
             q="True or False: The Large Intestine channel begins at the tip of the index finger.",
             opts=["True", "False"], ans="A",
             exp="LI1 (Shangyang) begins at the radial side of the tip of the index finger, at the nail corner - the same finger where the LU channel's branch terminates."),
        dict(n=11, type="EXCEPT",
             q="All of the following statements about LU and LI are true EXCEPT:",
             opts=["Both belong to the Metal element", "LU flows from chest to hand",
                   "LI flows from hand to head", "LI has fewer total acupoints than LU"], ans="D",
             exp="This is reversed - LI actually has MORE points than LU (20 vs. 11), even though LI is the Yang/Fu partner. Point count doesn't track Yin/Yang status consistently across pairs."),
    ]),
    ("STOMACH & SPLEEN", "Week 3", [
        dict(n=12, type="MC",
             q="What is the direction of Qi flow in all three foot-YANG meridians, including Stomach?",
             opts=["Foot to chest", "Chest to hand", "Hand to head", "Head to foot"], ans="D",
             exp="Foot Yang meridians all flow downward, head to foot. ST is a foot-Yang channel, so it follows this rule."),
        dict(n=13, type="MC",
             q="ST and SP both belong to which Five-Phase element?",
             opts=["Water", "Fire", "Earth", "Metal"], ans="C",
             exp="ST and SP form the Earth-element interior-exterior pair, active mid-morning (ST 7-9 AM, SP 9-11 AM)."),
        dict(n=14, type="MC",
             q="ST36 (Zusanli) is significant for holding which special-point categories?",
             opts=["Yuan-Source + Xi-Cleft", "He-Sea + Command Point (abdomen)",
                   "Luo-Connecting + Confluent", "Jing-Well + Luo-Connecting"], ans="B",
             exp="ST36 is the He-Sea point of ST and a Command Point for the abdomen. Dr. Zhang cited Nature-published studies showing ST36 can relieve inflammation and tonify Qi/Blood almost immediately - the #1 tonic point in TCM."),
        dict(n=15, type="MC",
             q="SP6 (Sanyinjiao) is significant because it is:",
             opts=["The Front-Mu of Spleen, safe in pregnancy",
                   "The crossing point of the 3 leg-Yin channels (SP/LR/KI), FORBIDDEN in pregnancy",
                   "The He-Sea point of SP, used only for edema",
                   "The Yuan-Source of SP, used only for digestion"], ans="B",
             exp="SP6 unites SP, LR, and KI - the three leg-Yin channels. Its strong descending/moving action on Blood makes it FORBIDDEN in pregnancy, alongside LI4."),
        dict(n=16, type="TF",
             q="True or False: SP4 (Gongsun) opens the Chong Mai and is paired with PC6 in the confluent point system.",
             opts=["True", "False"], ans="A",
             exp="SP4 is SP's Luo-Connecting point and also a Confluent point opening the Chong Mai. It classically pairs with PC6 (Neiguan) - together treating chest, heart, and stomach disorders."),
        dict(n=17, type="EXCEPT",
             q="All of the following are true of the Stomach channel EXCEPT:",
             opts=["It has 45 acupoints", "Its peak Qi time is 7-9 AM",
                   "It has 11 crossing points, the most of any primary channel",
                   "It begins at ST1 (Chengqi)"], ans="D",
             exp="The ST pathway actually originates at LI20 (Yingxiang), a crossing point of the LI channel on the face - ST1 is simply the first numbered point along that pathway, not the true starting point."),
    ]),
    ("HEART & SMALL INTESTINE", "Week 4", [
        dict(n=18, type="MC",
             q="The Heart channel's full classification is:",
             opts=["Hand Shaoyin", "Hand Taiyang", "Foot Shaoyin", "Foot Taiyang"], ans="A",
             exp="HT = Hand Shaoyin, Fire, Yin, peak 11 AM-1 PM. Its paired channel SI = Hand Taiyang, Fire, Yang, peak 1-3 PM. Together HT/SI form the Fire pair opening the Posterior Circuit (also called Inner Circuit)."),
        dict(n=19, type="MC",
             q="How many acupoints does the Heart channel have?",
             opts=["9", "11", "19", "20"], ans="A",
             exp="HT has only 9 points (HT1 Jiquan to HT9 Shaochong) - the fewest of any primary channel. Its paired SI channel has 19, more than double."),
        dict(n=20, type="MC",
             q="HT7 (Shenmen) is significant for holding which special categories?",
             opts=["He-Sea + Luo-Connecting", "Shu-Stream + Yuan-Source",
                   "Jing-Well + Xi-Cleft", "Front-Mu + Back-Shu"], ans="B",
             exp="HT7 is both the Shu-Stream and Yuan-Source point of HT - on Yin channels these two categories always coincide at the same point. HT7 calms the Shen and is a primary point for anxiety and insomnia."),
        dict(n=21, type="MC",
             q="SI3 (Houxi) is best described as:",
             opts=["The Yuan-Source point of SI, opening the Ren Mai",
                   "The Shu-Stream point of SI, also a Confluent point opening the Du Mai",
                   "The He-Sea point of SI, opening the Chong Mai",
                   "The Jing-Well point of SI, opening the Yin Wei Mai"], ans="B",
             exp="SI3 is SI's Shu-Stream point and doubles as a Confluent point opening the Du Mai - useful for spine, neck, and febrile conditions."),
        dict(n=22, type="TF",
             q="True or False: The Small Intestine channel has more total acupoints than the Heart channel.",
             opts=["True", "False"], ans="A",
             exp="SI has 19 points vs. HT's 9 - SI has more than double the points of its paired Yin channel, the same pattern seen with LU (11) / LI (20)."),
        dict(n=23, type="EXCEPT",
             q="All of the following statements about the Posterior Circuit (also called Inner Circuit) are true EXCEPT:",
             opts=["It includes HT, SI, BL, and KI", "HT and SI belong to the Fire element within this circuit",
                   "Peak Qi times for HT/SI/BL/KI run consecutively from 11 AM through 7 PM",
                   "PC and SJ are also part of this circuit"], ans="D",
             exp="PC (Pericardium) and SJ (San Jiao) form their own Ministerial Fire pairing and circuit, distinct from the Posterior/Inner Circuit of HT-SI-BL-KI. HT/SI are primary Fire; PC/SJ are Ministerial Fire - different circuits."),
    ]),
    ("CUMULATIVE / CROSS-CHANNEL", "Weeks 1-4", [
        dict(n=24, type="MC",
             q="Which Back-Shu point on the Bladder channel corresponds to the Spleen?",
             opts=["BL18", "BL20", "BL21", "BL25"], ans="B",
             exp="BL20 (Pishu) = Back-Shu of Spleen. Don't confuse it with BL21 (Weishu) = Back-Shu of Stomach - these sit right next to each other on the back and are commonly mixed up on exams."),
        dict(n=25, type="MC",
             q="Which point below is FORBIDDEN in pregnancy?",
             opts=["LI4 (Hegu)", "ST36 (Zusanli)", "HT7 (Shenmen)", "SI3 (Houxi)"], ans="A",
             exp="Within the Weeks 1-4 scope, only two points carry a pregnancy-forbidden flag: LI4 (Hegu) and SP6 (Sanyinjiao). Both have strong Qi/Blood-moving, descending actions."),
        dict(n=26, type="TF",
             q="True or False: The Anterior Circuit runs LU -> LI -> ST -> SP, in that order.",
             opts=["True", "False"], ans="A",
             exp="Correct Anterior Circuit sequence: chest to hand (LU), hand to head (LI), head to foot (ST), foot to chest (SP) - each channel handing Qi to the next."),
        dict(n=27, type="MC",
             q="Following the 24-hour circadian Qi cycle, which channel receives Qi directly after the Spleen (9-11 AM)?",
             opts=["Heart (11 AM-1 PM)", "Small Intestine (1-3 PM)", "Stomach (7-9 AM)", "Large Intestine (5-7 AM)"], ans="A",
             exp="SP's internal branch travels through the diaphragm into the Heart, handing Qi off to HT at 11 AM - the start of the Posterior/Inner Circuit."),
        dict(n=28, type="EXCEPT",
             q="All of the following are Yuan-Source points EXCEPT:",
             opts=["LU9 (Taiyuan)", "LI4 (Hegu)", "SP3 (Taibai)", "ST36 (Zusanli)"], ans="D",
             exp="ST36 is the He-Sea point and a Command Point for the abdomen - NOT the Yuan-Source of Stomach. ST's actual Yuan-Source point is ST42 (Chongyang). Don't let ST36's fame as the '#1 tonic point' cause you to misassign it as Yuan-Source."),
    ]),
]

TOTAL_Q = sum(len(qs) for _, _, qs in SECTIONS)
