# AC300 Practice Midterm SET 2 - Weeks 1-4 cumulative
# 28 questions, balanced across all 4 weeks (Theory/LU-LI/ST-SP/HT-SI get 6 each,
# 5 cumulative) - NO overlap with Practice Midterm Set 1.
# Several items incorporate facts directly confirmed from Dr. Zhang's own
# quiz-review sections in the lecture transcripts (Quiz 1, 2, 3 reviews +
# the Week 4 midterm-review dump).

SECTIONS = [
    ("CHANNEL THEORY & CIRCADIAN CLOCK", "Week 1", [
        dict(n=1, type="MC",
             q="Where do Foot Yin and Hand Yin meridians meet each other?",
             opts=["The fingers", "The face", "The toes", "The chest"], ans="D",
             exp="Foot Yin meets Hand Yin at the chest - completing the full 12-channel loop. (Hand Yin meets Hand Yang at the fingers; Hand Yang meets Foot Yang at the face; Foot Yang meets Foot Yin at the toes.)"),
        dict(n=2, type="TF",
             q="True or False: Zang organs are Yin and Fu organs are Yang.",
             opts=["True", "False"], ans="A",
             exp="Zang (Lung, Heart, Spleen, Liver, Kidney, Pericardium) are the Yin/solid organs. Fu (Large Intestine, Small Intestine, Stomach, Gallbladder, Bladder, San Jiao) are the Yang/hollow organs."),
        dict(n=3, type="EXCEPT",
             q="All of the following are Yang meridians EXCEPT:",
             opts=["Large Intestine", "Stomach", "Spleen", "Small Intestine"], ans="C",
             exp="Spleen (SP) is a Yin/Zang channel (Foot Taiyin). LI, ST, and SI are all Yang/Fu channels."),
        dict(n=4, type="MC",
             q="LU and LI belong to which of the three circuits?",
             opts=["Anterior (Taiyin/Yangming)", "Middle (Jueyin/Shaoyang)",
                   "Posterior (Shaoyin/Taiyang)", "None - they are a separate category"], ans="A",
             exp="LU (Taiyin) and LI (Yangming) form the Anterior circuit, alongside ST and SP."),
        dict(n=5, type="MC",
             q="Per Dr. Zhang's own Quiz 1 answer key, the three-part nomenclature is tested in which order?",
             opts=["Yin/Yang, Hand/Foot, Zang-Fu", "Zang-Fu, Hand/Foot, Yin/Yang",
                   "Hand/Foot, Zang-Fu, Yin/Yang", "Order does not matter"], ans="B",
             exp="Dr. Zhang's own confirmed answer key lists the three nomenclature features as Zang-Fu, Hand/Foot, Yin/Yang - a guaranteed-format question directly from her Quiz 1 review."),
        dict(n=6, type="MC",
             q="How many total primary meridians make up the full 24-hour circadian clock?",
             opts=["10", "12", "14", "15"], ans="B",
             exp="12 Primary Meridians (3 Hand Yin + 3 Hand Yang + 3 Foot Yin + 3 Foot Yang), confirmed repeatedly across Dr. Zhang's quiz reviews as a guaranteed topic."),
    ]),
    ("LUNG & LARGE INTESTINE", "Week 2", [
        dict(n=7, type="MC",
             q="Per Dr. Zhang's own Quiz 2 review, what is the pertaining organ of the Large Intestine channel?",
             opts=["Lung", "Stomach", "Large Intestine itself", "Small Intestine"], ans="C",
             exp="Confirmed directly from the Quiz 2 review: the pertaining organ of a channel is its own organ - for LI, that is the Large Intestine itself. 'Pertains' and 'connects' are often confused; pertains = own organ, connects = paired organ."),
        dict(n=8, type="MC",
             q="Per Dr. Zhang's own Quiz 2 review, where does the Large Intestine channel's running course end?",
             opts=["The index finger", "The opposite side of the nose (LI20)",
                   "The corner of the mouth", "The ear"], ans="B",
             exp="Confirmed directly from lecture: LI's pathway ends at LI20 Yingxiang, beside the nostril - on the OPPOSITE side of the body from where the branch crossed at the philtrum."),
        dict(n=9, type="MC",
             q="Per Dr. Zhang's own Quiz 2 review, what is the connecting organ of the Large Intestine channel?",
             opts=["Lung", "Stomach", "Spleen", "Heart"], ans="A",
             exp="Confirmed directly from lecture: LI's connecting organ is the Lung - its interior-exterior paired organ."),
        dict(n=10, type="MC",
             q="Per Dr. Zhang's own Quiz 2 review, which meridian passes along the lateral-anterior aspect of the forearm?",
             opts=["Lung (Hand Taiyin)", "Large Intestine (Hand Yangming)",
                   "Heart (Hand Shaoyin)", "Small Intestine (Hand Taiyang)"], ans="B",
             exp="Confirmed directly from lecture: the Large Intestine (Hand Yangming) channel runs along the lateral-anterior forearm. LU runs the MEDIAL-anterior forearm - the two are easy to swap on an exam."),
        dict(n=11, type="TF",
             q="True or False: The Lung channel's pathway runs along the medial-anterior border of the upper limb.",
             opts=["True", "False"], ans="A",
             exp="Confirmed directly from lecture: LU's exterior course runs the medial-anterior border of the arm - anterior because it's part of the Anterior circuit, medial because it's a Yin channel."),
        dict(n=12, type="EXCEPT",
             q="All of the following are true about LI's crossing points EXCEPT:",
             opts=["LI crosses GV14 Dazhui", "LI crosses GV26 Shuigou",
                   "LI crosses ST4 Dicang", "LI has only 1 total crossing point"], ans="D",
             exp="Confirmed directly from lecture: LI has FOUR crossing points (GV14, GV26, ST4, and a Small Intestine channel point near the face) - not just one. This is more crossing points than any other channel covered so far except ST."),
    ]),
    ("STOMACH & SPLEEN", "Week 3", [
        dict(n=13, type="MC",
             q="Per Dr. Zhang's own Quiz 3 review, does the Stomach meridian connect with the Lung?",
             opts=["Yes, via a minor branch", "No - ST connects with the Spleen, not the Lung",
                   "Yes, they share a crossing point", "The connection is only internal, not external"], ans="B",
             exp="Dr. Zhang specifically flagged this as a common misconception during the Quiz 3 review: the Stomach channel does NOT connect with the Lung. ST's connecting organ is the Spleen (its interior-exterior pair)."),
        dict(n=14, type="MC",
             q="What is the pertaining organ of the Stomach channel?",
             opts=["Spleen", "Stomach itself", "Large Intestine", "Small Intestine"], ans="B",
             exp="Following the same pattern as LI: the pertaining organ is always the channel's own organ. For ST, that's the Stomach itself; the Spleen is only the connecting (paired) organ."),
        dict(n=15, type="TF",
             q="True or False: ST and SP both belong to the Earth element.",
             opts=["True", "False"], ans="A",
             exp="ST (Foot Yangming) and SP (Foot Taiyin) form the Earth-element interior-exterior pair, active mid-morning (ST 7-9 AM, SP 9-11 AM)."),
        dict(n=16, type="MC",
             q="Where does the Stomach channel's pathway begin?",
             opts=["ST1 Chengqi, below the eye", "LI20 Yingxiang, beside the nose (a crossing point)",
                   "GV14 Dazhui", "ST36 Zusanli"], ans="B",
             exp="The ST pathway actually originates at LI20, a crossing point of the LI channel on the face - ST1 is simply the first numbered point along the pathway that follows, not the true starting point."),
        dict(n=17, type="MC",
             q="Where does the Stomach channel's pathway end?",
             opts=["ST36 at the knee", "ST45, at the lateral side of the 2nd toe",
                   "ST25 at the umbilicus", "ST1 below the eye"], ans="B",
             exp="ST45 Lidui, at the lateral side of the tip of the 2nd toe, is the last point of the Stomach channel - handing off to the Spleen channel, which begins at the big toe (SP1)."),
        dict(n=18, type="EXCEPT",
             q="All of the following are true of the Spleen channel EXCEPT:",
             opts=["It has 21 acupoints", "It is a Foot Taiyin channel",
                   "It connects to the Stomach", "It has 11 crossing points, the most of any channel"], ans="D",
             exp="SP has 6 crossing points, not 11 - the ST channel is the one with 11 crossing points (the most of any primary channel). Don't confuse the two Earth-element partners' crossing-point counts."),
    ]),
    ("HEART & SMALL INTESTINE", "Week 4", [
        dict(n=19, type="MC",
             q="At which finger do the Heart and Small Intestine channels meet?",
             opts=["The middle finger", "The ring finger", "The little finger", "The index finger"], ans="C",
             exp="HT9 and SI1 meet at the LITTLE finger - the correct, verified answer (a lecture transcript passage that seemed to say 'middle finger' was a transcription error; the little-finger meeting point is independently confirmed in the existing Midterm Cram Sheet)."),
        dict(n=20, type="MC",
             q="What is the pertaining organ of the Small Intestine channel?",
             opts=["Heart", "Small Intestine itself", "Bladder", "Stomach"], ans="B",
             exp="Same pattern as every other channel: the pertaining organ is always the channel's own organ. The Heart is only SI's connecting (paired) organ."),
        dict(n=21, type="MC",
             q="What is the connecting organ of the Heart channel?",
             opts=["Small Intestine", "Bladder", "Pericardium", "San Jiao"], ans="A",
             exp="HT's connecting organ is the Small Intestine - its Fire-element interior-exterior pair."),
        dict(n=22, type="TF",
             q="True or False: The Heart channel has zero crossing points.",
             opts=["True", "False"], ans="A",
             exp="Confirmed and unique: HT is the only one of the 12 primary channels with no crossing points on its external pathway."),
        dict(n=23, type="MC",
             q="SI's Lower He-Sea point sits on which channel?",
             opts=["SI itself", "The Bladder channel", "The Stomach channel", "The Gallbladder channel"], ans="C",
             exp="SI's Lower He-Sea is ST39 Xiajuxu, located on the Stomach channel - not on SI itself. Lower He-Sea points for the six Fu organs all sit on the leg-Yang channels."),
        dict(n=24, type="EXCEPT",
             q="All of the following are true about HT and SI EXCEPT:",
             opts=["HT has 9 points, SI has 19", "Both belong to the Fire element",
                   "SI3 is a Confluent point", "SI3 opens the Ren Mai"], ans="D",
             exp="SI3 Houxi opens the DU MAI, not the Ren Mai. This is a frequently confused pairing - remember SI3 pairs with BL62 to open the Du Mai."),
    ]),
    ("CUMULATIVE / CROSS-CHANNEL", "Weeks 1-4", [
        dict(n=25, type="MC",
             q="Following the circadian clock, what comes immediately after Stomach and Spleen (7-11 AM)?",
             opts=["Heart and Small Intestine (11 AM-3 PM)", "Bladder and Kidney (3-7 PM)",
                   "Lung and Large Intestine (3-7 AM)", "Pericardium and San Jiao (7-11 PM)"], ans="A",
             exp="The full sequence is LU-LI-ST-SP-HT-SI-BL-KI-PC-SJ-GB-LR. After SP (9-11 AM) comes HT (11 AM-1 PM), then SI (1-3 PM) - the Fire pair opening the Posterior Circuit."),
        dict(n=26, type="MC",
             q="Where do Foot Yang and Foot Yin meridians meet each other?",
             opts=["The chest", "The face", "The toes", "The fingers"], ans="C",
             exp="Foot Yang meets Foot Yin at the toes (e.g., ST45 to SP1). Foot Yin then continues to meet Hand Yin at the chest, completing the loop."),
        dict(n=27, type="TF",
             q="True or False: LI4 and SP6 are both forbidden in pregnancy.",
             opts=["True", "False"], ans="A",
             exp="Within the Weeks 1-4 scope, these are the only two points carrying a pregnancy-forbidden flag: LI4 (Hegu) and SP6 (Sanyinjiao) - both have strong Qi/Blood-moving, descending actions."),
        dict(n=28, type="MC",
             q="LI's Front-Mu point is ST25, located on which channel?",
             opts=["LI's own channel", "The Stomach channel", "The Bladder channel", "The Spleen channel"], ans="B",
             exp="LI's Front-Mu is ST25 Tianshu, on the STOMACH channel - not on LI itself. Contrast this with LU, which has its OWN Front-Mu at LU1."),
    ]),
]

TOTAL_Q = sum(len(qs) for _, _, qs in SECTIONS)
